title: "Mukhil C"
description: " Hi! I'm Mukhil C, and I work on gravitational physics including gravitational-wave astrophysics.  
This website hosts my research summaries, Master's thesis, posters, and CV."
theme: jekyll-theme-cayman
 
markdown: kramdown
kramdown:
  input: GFM
