title: Welcome
description: "Hi! I'm Mukhil C. I currently work in the field of gravitational physics, particularly multi-body dynamics and gravitational waves. I sometimes do go on side-quests in the field too. "
theme: jekyll-theme-cayman
