title: "Mukhil C"
description: "Research in Gravitational Physics and Gravitational Waves"
theme: jekyll-theme-minimal

# Navigation bar
header_pages:
  - index.md
  - research.md
 
markdown: kramdown
kramdown:
  input: GFM
