title: Welcome
description: "Hi! I'm Mukhil C. I currently work in the field of gravitational physics, particularly multi-body dynamicsa and gravitational waves. I sometimes do go on side-quests in the field too. "
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
